name: "Build and push Docker Image to GPASLTD OCIR"
run-name: "${{ github.repository }} release build"
concurrency: "${{ github.repository }}-release"

on:
  release:
    types: [ published ]

jobs:
  build-and-push:
    uses: EIT-Pathogena/common-workflows/.github/workflows/build-and-push-to-ocir.yml@main
    with:
      repository: ${{ github.repository }}
      image_tag: ${{ github.event.release.tag_name }}
